/**
 * ServerSettings - Server-authoritative settings persistence.
 *
 * Owns settings that affect server-side behavior. The web app can continue to
 * keep UI-only preferences in local storage while these values become durable
 * and process-authoritative on the server.
 */
import {
  DEFAULT_AGENT_GROUP_PROMPT_INSTRUCTIONS,
  DEFAULT_MODEL_BY_PROVIDER,
  DEFAULT_SERVER_SETTINGS,
  type AgentGroupPromptInstructions,
  type ModelSelection,
  type ProviderWithDefaultModel,
  ServerSettings,
  ServerSettingsError,
  type ServerSettingsPatch,
} from "@agent-group/contracts";
import { deepMerge, type DeepPartial } from "@agent-group/shared/Struct";
import { CONTEXT_TEMPLATE_PRESETS } from "@agent-group/shared/contextTemplates";
import { applyServerSettingsPatch } from "@agent-group/shared/serverSettings";
import {
  Cause,
  Deferred,
  Effect,
  FileSystem,
  Layer,
  Path,
  PubSub,
  Ref,
  Schema,
  SchemaIssue,
  ServiceMap,
  Stream,
} from "effect";
import * as Semaphore from "effect/Semaphore";
import { ServerConfig } from "./config";

export interface ServerSettingsShape {
  readonly start: Effect.Effect<void, ServerSettingsError>;
  readonly ready: Effect.Effect<void, ServerSettingsError>;
  readonly getSettings: Effect.Effect<ServerSettings, ServerSettingsError>;
  readonly updateSettings: (
    patch: ServerSettingsPatch,
  ) => Effect.Effect<ServerSettings, ServerSettingsError>;
  readonly streamChanges: Stream.Stream<ServerSettings>;
}

export class ServerSettingsService extends ServiceMap.Service<
  ServerSettingsService,
  ServerSettingsShape
>()("agent-group/serverSettings/ServerSettingsService") {
  static readonly layerTest = (overrides: DeepPartial<ServerSettings> = {}) =>
    Layer.effect(
      ServerSettingsService,
      Effect.gen(function* () {
        const currentSettingsRef = yield* Ref.make<ServerSettings>(
          withDefaultAgentGroupTemplates(deepMerge(DEFAULT_SERVER_SETTINGS, overrides)),
        );
        const changesPubSub = yield* PubSub.unbounded<ServerSettings>();
        const emitChange = (settings: ServerSettings) =>
          PubSub.publish(changesPubSub, settings).pipe(Effect.asVoid);

        return {
          start: Effect.void,
          ready: Effect.void,
          getSettings: Ref.get(currentSettingsRef).pipe(Effect.map(resolveTextGenerationProvider)),
          updateSettings: (patch) =>
            Ref.get(currentSettingsRef).pipe(
              Effect.flatMap((currentSettings) =>
                normalizeSettings("<memory>", currentSettings, patch),
              ),
              Effect.tap((nextSettings) => Ref.set(currentSettingsRef, nextSettings)),
              Effect.tap(emitChange),
              Effect.map(resolveTextGenerationProvider),
            ),
          get streamChanges() {
            return Stream.fromPubSub(changesPubSub).pipe(Stream.map(resolveTextGenerationProvider));
          },
        } satisfies ServerSettingsShape;
      }),
    );
}

const PROVIDER_ORDER: readonly ProviderWithDefaultModel[] = [
  "codex",
  "claudeAgent",
  "kilo",
  "opencode",
];

const LEGACY_AGENT_GROUP_PROMPT_INSTRUCTIONS: {
  readonly [Key in keyof AgentGroupPromptInstructions]: readonly string[];
} = {
  sessionContextFirstTurn: [
    "Read before work. Maintain this file as your session context; edit only this file.",
    "Read before work. Keep this file current for continuity; do not edit other Session context files.",
    "Persistent context for this Session across turns and Agents.",
    "Maintain this file as the current Session context.",
  ],
  sessionContextLaterTurn: [
    "Maintain this file as your session context; edit only this file.",
    "Read if not already loaded. Keep this file current for continuity; do not edit other Session context files.",
    "Persistent context for this Session across turns and Agents.",
    "Maintain this file as the current Session context.",
  ],
  parentContext: [
    "Read before work for background.",
    "Read only for background; do not edit this file.",
    "Background context inherited from the parent Session.",
  ],
  mentionedSessions: [
    "Read only as needed.",
    "Open only when relevant; do not edit referenced Session context files.",
    "Server-resolved context and transcript references for mentioned Sessions.",
  ],
  contextChanges: [
    "Run only if needed:",
    "Run only when relevant:",
    "Unseen Session context changes available from Context Git.",
    "Command for checking recent Session context changes:",
  ],
  browserTools: [
    "Read its help only when needed.",
    "Check help only when needed.",
    "Browser automation available to this Session.",
  ],
};

function migrateAgentGroupPromptDefaults(settings: ServerSettings): ServerSettings {
  const current = settings.agentGroup.promptInstructions;
  const migrate = (key: keyof AgentGroupPromptInstructions) =>
    LEGACY_AGENT_GROUP_PROMPT_INSTRUCTIONS[key].includes(current[key])
      ? DEFAULT_AGENT_GROUP_PROMPT_INSTRUCTIONS[key]
      : current[key];
  return withDefaultAgentGroupTemplates({
    ...settings,
    agentGroup: {
      ...settings.agentGroup,
      promptInstructions: {
        sessionContextFirstTurn: migrate("sessionContextFirstTurn"),
        sessionContextLaterTurn: migrate("sessionContextLaterTurn"),
        parentContext: migrate("parentContext"),
        mentionedSessions: migrate("mentionedSessions"),
        contextChanges: migrate("contextChanges"),
        browserTools: migrate("browserTools"),
      },
    },
  });
}

function withDefaultAgentGroupTemplates(settings: ServerSettings): ServerSettings {
  if (settings.agentGroup.contextTemplates.length > 0) return settings;
  return {
    ...settings,
    agentGroup: {
      ...settings.agentGroup,
      contextTemplates: CONTEXT_TEMPLATE_PRESETS.map((template) => ({ ...template })),
    },
  };
}

function resolveTextGenerationProvider(settings: ServerSettings): ServerSettings {
  const selection = settings.textGenerationModelSelection;
  if (settings.providers[selection.provider].enabled) {
    return settings;
  }

  const fallback = PROVIDER_ORDER.find((provider) => settings.providers[provider].enabled);
  if (!fallback) {
    return settings;
  }

  return {
    ...settings,
    textGenerationModelSelection: {
      provider: fallback,
      model: DEFAULT_MODEL_BY_PROVIDER[fallback],
    } as ModelSelection,
  };
}

function normalizeSettings(
  settingsPath: string,
  current: ServerSettings,
  patch: ServerSettingsPatch,
): Effect.Effect<ServerSettings, ServerSettingsError> {
  return Schema.decodeUnknownEffect(ServerSettings)(applyServerSettingsPatch(current, patch)).pipe(
    Effect.map(withDefaultAgentGroupTemplates),
    Effect.mapError(
      (cause) =>
        new ServerSettingsError({
          settingsPath,
          detail: `failed to normalize server settings: ${SchemaIssue.makeFormatterDefault()(cause.issue)}`,
          cause,
        }),
    ),
  );
}

function decodeSettingsFromJson(settingsPath: string, raw: string) {
  try {
    const decoded = Schema.decodeUnknownExit(ServerSettings)(JSON.parse(raw) as unknown);
    if (decoded._tag === "Failure") {
      return { _tag: "Failure" as const, error: Cause.pretty(decoded.cause) };
    }
    return {
      _tag: "Success" as const,
      value: migrateAgentGroupPromptDefaults(decoded.value),
    };
  } catch (cause) {
    const error = new ServerSettingsError({
      settingsPath,
      detail: "failed to parse settings JSON",
      cause,
    });
    return { _tag: "Failure" as const, error: error.message };
  }
}

const makeServerSettings = Effect.gen(function* () {
  const { settingsPath } = yield* ServerConfig;
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const writeSemaphore = yield* Semaphore.make(1);
  const changesPubSub = yield* PubSub.unbounded<ServerSettings>();
  const settingsRef = yield* Ref.make<ServerSettings>(DEFAULT_SERVER_SETTINGS);
  const startedRef = yield* Ref.make(false);
  const startedDeferred = yield* Deferred.make<void, ServerSettingsError>();

  const emitChange = (settings: ServerSettings) =>
    PubSub.publish(changesPubSub, settings).pipe(Effect.asVoid);

  const loadSettingsFromDisk = Effect.gen(function* () {
    const exists = yield* fs.exists(settingsPath).pipe(
      Effect.mapError(
        (cause) =>
          new ServerSettingsError({
            settingsPath,
            detail: "failed to check settings file existence",
            cause,
          }),
      ),
    );
    if (!exists) {
      return withDefaultAgentGroupTemplates(DEFAULT_SERVER_SETTINGS);
    }

    const raw = yield* fs.readFileString(settingsPath).pipe(
      Effect.mapError(
        (cause) =>
          new ServerSettingsError({
            settingsPath,
            detail: "failed to read settings file",
            cause,
          }),
      ),
    );
    const decoded = decodeSettingsFromJson(settingsPath, raw);
    if (decoded._tag === "Failure") {
      yield* Effect.logWarning("failed to parse settings.json, using defaults", {
        path: settingsPath,
        error: decoded.error,
      });
      return withDefaultAgentGroupTemplates(DEFAULT_SERVER_SETTINGS);
    }
    return decoded.value;
  });

  const writeSettingsAtomically = (settings: ServerSettings) => {
    const tempPath = `${settingsPath}.${process.pid}.${Date.now()}.tmp`;
    return Effect.gen(function* () {
      yield* fs.makeDirectory(path.dirname(settingsPath), { recursive: true });
      yield* fs.writeFileString(tempPath, `${JSON.stringify(settings, null, 2)}\n`);
      yield* fs.rename(tempPath, settingsPath);
    }).pipe(
      Effect.mapError(
        (cause) =>
          new ServerSettingsError({
            settingsPath,
            detail: "failed to write settings file",
            cause,
          }),
      ),
    );
  };

  const start = Effect.gen(function* () {
    const shouldStart = yield* Ref.modify(startedRef, (started) => [!started, true]);
    if (!shouldStart) {
      return yield* Deferred.await(startedDeferred);
    }

    const startup = Effect.gen(function* () {
      yield* fs.makeDirectory(path.dirname(settingsPath), { recursive: true }).pipe(
        Effect.mapError(
          (cause) =>
            new ServerSettingsError({
              settingsPath,
              detail: "failed to prepare settings directory",
              cause,
            }),
        ),
      );
      const settings = yield* loadSettingsFromDisk;
      yield* Ref.set(settingsRef, settings);
    });

    const startupExit = yield* Effect.exit(startup);
    if (startupExit._tag === "Failure") {
      yield* Deferred.failCause(startedDeferred, startupExit.cause).pipe(Effect.orDie);
      return yield* Effect.failCause(startupExit.cause);
    }

    yield* Deferred.succeed(startedDeferred, undefined).pipe(Effect.orDie);
  });

  return {
    start,
    ready: Deferred.await(startedDeferred),
    getSettings: Ref.get(settingsRef).pipe(Effect.map(resolveTextGenerationProvider)),
    updateSettings: (patch) =>
      writeSemaphore.withPermits(1)(
        Effect.gen(function* () {
          const current = yield* Ref.get(settingsRef);
          const next = yield* normalizeSettings(settingsPath, current, patch);
          yield* writeSettingsAtomically(next);
          yield* Ref.set(settingsRef, next);
          yield* emitChange(next);
          return resolveTextGenerationProvider(next);
        }),
      ),
    get streamChanges() {
      return Stream.fromPubSub(changesPubSub).pipe(Stream.map(resolveTextGenerationProvider));
    },
  } satisfies ServerSettingsShape;
});

export const ServerSettingsLive = Layer.effect(ServerSettingsService, makeServerSettings);
