export type {
  BrowserAttachWebviewInput,
  BrowserCaptureScreenshotResult,
  BrowserCopyLinkEvent,
  BrowserDetachWebviewInput,
  BrowserExecuteCdpInput,
  BrowserNavigateInput,
  BrowserNewTabInput,
  BrowserOpenInput,
  BrowserPanelBounds,
  BrowserSetPanelBoundsInput,
  BrowserTabInput,
  BrowserTabState,
  BrowserThreadInput,
  ContextMenuItem,
  DesktopAppSnapCapture,
  DesktopAppSnapErrorEvent,
  DesktopAppSnapPermission,
  DesktopAppSnapPlatform,
  DesktopAppSnapState,
  DesktopAppSnapStatus,
  DesktopBridge,
  DesktopNotificationInput,
  DesktopRuntimeArch,
  DesktopRuntimeInfo,
  DesktopTheme,
  DesktopUpdateActionResult,
  DesktopUpdateState,
  DesktopUpdateStatus,
  DesktopWindowState,
  AgentGroupStorageSnapshot,
  ThreadBrowserState,
} from "./ipc/desktop";
export type { NativeApi } from "./ipc/nativeApi";
