// Compatibility facade. Domain schemas live under ./orchestration/.
export {
  ORCHESTRATION_WS_METHODS,
  ORCHESTRATION_WS_CHANNELS,
  ProviderKind,
  ProviderApprovalPolicy,
  ProviderSandboxMode,
  DEFAULT_PROVIDER_KIND,
  CodexModelSelection,
  ClaudeModelSelection,
  CursorModelSelection,
  AntigravityModelSelection,
  GrokModelSelection,
  DroidModelSelection,
  OpenCodeModelSelection,
  KiloModelSelection,
  PiModelSelection,
  ModelSelection,
  CodexProviderStartOptions,
  ClaudeProviderStartOptions,
  AntigravityProviderStartOptions,
  CursorProviderStartOptions,
  GrokProviderStartOptions,
  DroidProviderStartOptions,
  OpenCodeProviderStartOptions,
  KiloProviderStartOptions,
  PiProviderStartOptions,
  ProviderStartOptions,
  RuntimeMode,
  DEFAULT_RUNTIME_MODE,
  ProviderInteractionMode,
  DEFAULT_PROVIDER_INTERACTION_MODE,
  ProviderRequestKind,
  AssistantDeliveryMode,
  TurnDispatchMode,
  DEFAULT_TURN_DISPATCH_MODE,
  MessageDispatchOrigin,
  ProviderReviewTarget,
  ProviderApprovalDecision,
  ProviderUserInputAnswer,
  ProviderUserInputAnswers,
  ThreadHandoffBootstrapStatus,
  ThreadEnvironmentMode,
  OrchestrationMessageSource,
  PROVIDER_SEND_TURN_MAX_INPUT_CHARS,
  PROVIDER_SEND_TURN_MAX_ATTACHMENTS,
  PROVIDER_SEND_TURN_MAX_IMAGE_BYTES,
  PROVIDER_SEND_TURN_MAX_FILE_BYTES,
  MAX_PINNED_PROJECTS,
  CHAT_ASSISTANT_SELECTION_TEXT_MAX_CHARS,
  THREAD_NOTES_MAX_CHARS,
  PINNED_MESSAGES_MAX_COUNT,
  PINNED_MESSAGE_LABEL_MAX_CHARS,
  THREAD_MARKERS_MAX_COUNT,
  THREAD_MARKER_LABEL_MAX_CHARS,
  THREAD_MARKER_SELECTED_TEXT_MAX_CHARS,
  THREAD_MARKER_CONTEXT_MAX_CHARS,
  THREAD_MARKER_NOTE_MAX_CHARS,
  CorrelationId,
} from "./orchestration/protocol";
export {
  ChatImageAttachment,
  ChatFileAttachment,
  ChatAssistantSelectionAttachment,
  UploadChatFileAttachment,
  UploadChatAssistantSelectionAttachment,
  ChatAttachment,
} from "./orchestration/attachments";
export type {
  ChatAttachmentId,
  UploadChatImageAttachment,
  UploadChatAttachment,
} from "./orchestration/attachments";
export {
  ProjectScriptIcon,
  ProjectScript,
  OrchestrationProject,
  OrchestrationProjectShell,
  OrchestrationMessageRole,
  OrchestrationMessage,
  ThreadHandoff,
  OrchestrationProposedPlanId,
  OrchestrationProposedPlan,
  OrchestrationSessionStatus,
  OrchestrationSession,
  OrchestrationCheckpointFile,
  OrchestrationCheckpointStatus,
  OrchestrationCheckpointSummary,
  OrchestrationThreadActivityTone,
  OrchestrationThreadActivity,
  OrchestrationLatestTurn,
  OrchestrationThreadPullRequest,
  ThreadNotes,
  PinnedMessageLabel,
  PinnedMessage,
  ThreadPinnedMessages,
  ThreadMarkerStyle,
  ThreadMarkerColor,
  ThreadMarkerLabel,
  ThreadMarkerContext,
  ThreadMarkerNote,
  ThreadMarker,
  ThreadMarkers,
} from "./orchestration/readModelCore";
export type { OrchestrationLatestTurnState } from "./orchestration/readModelCore";
export {
  OrchestrationThread,
  OrchestrationThreadShell,
  OrchestrationReadModel,
  OrchestrationShellSnapshot,
  OrchestrationShellStreamEvent,
  OrchestrationShellStreamItem,
} from "./orchestration/readModels";
export {
  ProjectCreateCommand,
  ThreadHandoffImportedMessage,
} from "./orchestration/projectThreadCommandSchemas";
export { ThreadTurnStartCommand } from "./orchestration/turnCommandSchemas";
export { ClientOrchestrationCommand, OrchestrationCommand } from "./orchestration/commands";
export type {
  DispatchableClientOrchestrationCommand,
  InternalOrchestrationCommand,
} from "./orchestration/commands";
export {
  OrchestrationEventType,
  OrchestrationAggregateKind,
  OrchestrationActorKind,
  ProjectCreatedPayload,
  ProjectMetaUpdatedPayload,
  ProjectDeletedPayload,
  ThreadCreatedPayload,
  ThreadDeletedPayload,
  ThreadArchivedPayload,
  ThreadUnarchivedPayload,
  ThreadMetaUpdatedPayload,
  ThreadPinnedMessageAddedPayload,
  ThreadPinnedMessageRemovedPayload,
  ThreadPinnedMessageDoneSetPayload,
  ThreadPinnedMessageLabelSetPayload,
  ThreadMarkerAddedPayload,
  ThreadMarkerRemovedPayload,
  ThreadMarkerDoneSetPayload,
  ThreadMarkerLabelSetPayload,
  ThreadMarkerColorSetPayload,
  ThreadMarkerNoteSetPayload,
  ThreadRuntimeModeSetPayload,
  ThreadInteractionModeSetPayload,
  ThreadMessageSentPayload,
  ThreadTurnStartRequestedPayload,
  ThreadTurnQueuedPayload,
  ThreadTurnInterruptRequestedPayload,
  ThreadApprovalResponseRequestedPayload,
  ThreadCheckpointRevertRequestedPayload,
  ThreadRevertedPayload,
  ThreadConversationRollbackRequestedPayload,
  ThreadConversationRolledBackPayload,
  ThreadMessageEditResendRequestedPayload,
  ThreadSessionStopRequestedPayload,
  ThreadSessionSetPayload,
  ThreadProposedPlanUpsertedPayload,
  ThreadTurnDiffCompletedPayload,
  ThreadActivityAppendedPayload,
} from "./orchestration/eventPayloads";
export { OrchestrationEventMetadata, OrchestrationEvent } from "./orchestration/events";
export {
  OrchestrationThreadDetailSnapshot,
  OrchestrationThreadStreamItem,
  OrchestrationCommandReceiptStatus,
  TurnCountRange,
  ThreadTurnDiff,
  ProviderSessionRuntimeStatus,
  ProjectionPendingApprovalStatus,
  ProjectionPendingApprovalDecision,
  DispatchResult,
  OrchestrationGetSnapshotInput,
  OrchestrationGetShellSnapshotInput,
  OrchestrationRepairStateInput,
  OrchestrationGetTurnDiffInput,
  OrchestrationGetTurnDiffResult,
  OrchestrationGetFullThreadDiffInput,
  OrchestrationGetFullThreadDiffResult,
  OrchestrationReplayEventsInput,
  OrchestrationSubscribeShellInput,
  OrchestrationUnsubscribeShellInput,
  OrchestrationSubscribeThreadInput,
  OrchestrationImportThreadInput,
  OrchestrationImportThreadResult,
  OrchestrationUnsubscribeThreadInput,
  OrchestrationRpcSchemas,
} from "./orchestration/rpc";
export type {
  ProjectionThreadTurnStatus,
  ProjectionCheckpointRow,
  OrchestrationGetSnapshotResult,
  OrchestrationGetShellSnapshotResult,
  OrchestrationRepairStateResult,
  OrchestrationReplayEventsResult,
} from "./orchestration/rpc";
