import * as RpcGroup from "effect/unstable/rpc/RpcGroup";

import * as AutomationRpc from "./rpc/automationRpc";
import * as GitRpc from "./rpc/gitRpc";
import * as OrchestrationRpc from "./rpc/orchestrationRpc";
import * as ProjectRpc from "./rpc/projectRpc";
import * as ProviderRpc from "./rpc/providerRpc";
import * as ServerRpc from "./rpc/serverRpc";
import * as TerminalRpc from "./rpc/terminalRpc";

export * from "./rpc/automationRpc";
export * from "./rpc/errors";
export * from "./rpc/gitRpc";
export * from "./rpc/orchestrationRpc";
export * from "./rpc/projectRpc";
export * from "./rpc/providerRpc";
export * from "./rpc/serverRpc";
export * from "./rpc/terminalRpc";

export const WsRpcGroup = RpcGroup.make(
  OrchestrationRpc.WsDialogsPickFolderRpc,
  OrchestrationRpc.WsAgentGroupGetConfigRpc,
  OrchestrationRpc.WsAgentGroupGetOverviewRpc,
  OrchestrationRpc.WsAgentGroupGetSessionRpc,
  OrchestrationRpc.WsAgentGroupWriteContextRpc,
  OrchestrationRpc.WsAgentGroupUpdateConfigRpc,
  OrchestrationRpc.WsAgentGroupUpdateSessionRpc,
  OrchestrationRpc.WsOrchestrationDispatchCommandRpc,
  OrchestrationRpc.WsOrchestrationImportThreadRpc,
  OrchestrationRpc.WsOrchestrationGetSnapshotRpc,
  OrchestrationRpc.WsOrchestrationGetShellSnapshotRpc,
  OrchestrationRpc.WsOrchestrationListHighlightsRpc,
  OrchestrationRpc.WsOrchestrationRepairStateRpc,
  OrchestrationRpc.WsOrchestrationGetTurnDiffRpc,
  OrchestrationRpc.WsOrchestrationGetFullThreadDiffRpc,
  OrchestrationRpc.WsOrchestrationReplayEventsRpc,
  OrchestrationRpc.WsOrchestrationSubscribeShellRpc,
  OrchestrationRpc.WsOrchestrationUnsubscribeShellRpc,
  OrchestrationRpc.WsOrchestrationSubscribeThreadRpc,
  OrchestrationRpc.WsOrchestrationUnsubscribeThreadRpc,
  ProjectRpc.WsProjectsDiscoverScriptsRpc,
  ProjectRpc.WsProjectsListDirectoriesRpc,
  ProjectRpc.WsProjectsSearchEntriesRpc,
  ProjectRpc.WsProjectsSearchLocalEntriesRpc,
  ProjectRpc.WsProjectsReadFileRpc,
  ProjectRpc.WsProjectsCreateLocalFilePreviewGrantRpc,
  ProjectRpc.WsProjectsWriteFileRpc,
  ProjectRpc.WsProjectsRunDevServerRpc,
  ProjectRpc.WsProjectsStopDevServerRpc,
  ProjectRpc.WsProjectsListDevServersRpc,
  ProjectRpc.WsSubscribeProjectDevServerEventsRpc,
  ProjectRpc.WsStudioListThreadOutputsRpc,
  ProjectRpc.WsFilesystemBrowseRpc,
  ProjectRpc.WsShellOpenInEditorRpc,
  GitRpc.WsGitGithubRepositoryRpc,
  GitRpc.WsGitStatusRpc,
  GitRpc.WsGitReadWorkingTreeDiffRpc,
  GitRpc.WsGitSummarizeDiffRpc,
  GitRpc.WsGitPullRpc,
  GitRpc.WsGitRunStackedActionRpc,
  GitRpc.WsGitResolvePullRequestRpc,
  GitRpc.WsGitPullRequestSnapshotRpc,
  GitRpc.WsGitPreparePullRequestThreadRpc,
  GitRpc.WsPullRequestsListRpc,
  GitRpc.WsPullRequestsReviewRequestCountRpc,
  GitRpc.WsPullRequestsDetailRpc,
  GitRpc.WsPullRequestsDiffRpc,
  GitRpc.WsPullRequestsActionRpc,
  GitRpc.WsPullRequestsCommentRpc,
  GitRpc.WsPullRequestsSetPinnedRpc,
  GitRpc.WsGitListBranchesRpc,
  GitRpc.WsGitCreateWorktreeRpc,
  GitRpc.WsGitCreateDetachedWorktreeRpc,
  GitRpc.WsGitRemoveWorktreeRpc,
  GitRpc.WsGitCreateBranchRpc,
  GitRpc.WsGitCheckoutRpc,
  GitRpc.WsGitStashAndCheckoutRpc,
  GitRpc.WsGitStashDropRpc,
  GitRpc.WsGitStashInfoRpc,
  GitRpc.WsGitRemoveIndexLockRpc,
  GitRpc.WsGitInitRpc,
  GitRpc.WsGitStageFilesRpc,
  GitRpc.WsGitUnstageFilesRpc,
  GitRpc.WsGitHandoffThreadRpc,
  TerminalRpc.WsTerminalOpenRpc,
  TerminalRpc.WsTerminalWriteRpc,
  TerminalRpc.WsTerminalAckOutputRpc,
  TerminalRpc.WsTerminalResizeRpc,
  TerminalRpc.WsTerminalClearRpc,
  TerminalRpc.WsTerminalRestartRpc,
  TerminalRpc.WsTerminalCloseRpc,
  TerminalRpc.WsSubscribeTerminalEventsRpc,
  ServerRpc.WsServerGetConfigRpc,
  ServerRpc.WsServerGetEnvironmentRpc,
  ServerRpc.WsServerGetSettingsRpc,
  ServerRpc.WsServerUpdateSettingsRpc,
  ServerRpc.WsServerGetRemoteAccessStatusRpc,
  ServerRpc.WsServerRestartRemoteAccessRpc,
  ServerRpc.WsServerResetRemoteAccessRpc,
  ServerRpc.WsServerRefreshProvidersRpc,
  ServerRpc.WsServerUpdateProviderRpc,
  ServerRpc.WsServerListWorktreesRpc,
  ServerRpc.WsServerListLocalServersRpc,
  ServerRpc.WsServerStopLocalServerRpc,
  ServerRpc.WsServerGetProviderUsageSnapshotRpc,
  ServerRpc.WsServerListProviderUsageRpc,
  ServerRpc.WsStatsGetProfileStatsRpc,
  ServerRpc.WsStatsGetProfileTokenStatsRpc,
  ServerRpc.WsServerGetDiagnosticsRpc,
  ServerRpc.WsServerTranscribeVoiceRpc,
  ServerRpc.WsServerGenerateThreadRecapRpc,
  ServerRpc.WsServerGenerateAutomationIntentRpc,
  ServerRpc.WsServerUpsertKeybindingRpc,
  ServerRpc.WsSubscribeServerLifecycleRpc,
  ServerRpc.WsSubscribeServerConfigRpc,
  ServerRpc.WsSubscribeServerProviderStatusesRpc,
  ServerRpc.WsSubscribeServerSettingsRpc,
  ProviderRpc.WsProviderGetComposerCapabilitiesRpc,
  ProviderRpc.WsProviderCompactThreadRpc,
  ProviderRpc.WsProviderListCommandsRpc,
  ProviderRpc.WsProviderListSkillsRpc,
  ProviderRpc.WsProviderListSkillsCatalogRpc,
  ProviderRpc.WsProviderListPluginsRpc,
  ProviderRpc.WsProviderReadPluginRpc,
  ProviderRpc.WsProviderListModelsRpc,
  ProviderRpc.WsProviderListAgentsRpc,
  AutomationRpc.WsAutomationListRpc,
  AutomationRpc.WsAutomationCreateRpc,
  AutomationRpc.WsAutomationUpdateRpc,
  AutomationRpc.WsAutomationDeleteRpc,
  AutomationRpc.WsAutomationRunNowRpc,
  AutomationRpc.WsAutomationCancelRunRpc,
  AutomationRpc.WsAutomationMarkRunReadRpc,
  AutomationRpc.WsAutomationArchiveRunRpc,
  AutomationRpc.WsSubscribeAutomationEventsRpc,
);
