import type { ProviderKind } from "../providerKind";
import type { ModelSlug } from "./catalog";

export const MODEL_SLUG_ALIASES_BY_PROVIDER: Record<ProviderKind, Record<string, ModelSlug>> = {
  codex: {
    "5.5": "gpt-5.5",
    "5.4": "gpt-5.4",
    "5.3": "gpt-5.3-codex",
    "gpt-5.3": "gpt-5.3-codex",
    "5.3-spark": "gpt-5.3-codex-spark",
    "gpt-5.3-spark": "gpt-5.3-codex-spark",
  },
  claudeAgent: {
    fable: "claude-fable-5",
    "fable-5": "claude-fable-5",
    opus: "claude-opus-4-8",
    "opus-4.8": "claude-opus-4-8",
    "claude-opus-4.8": "claude-opus-4-8",
    "claude-opus-4-8-20260528": "claude-opus-4-8",
    "opus-4.7": "claude-opus-4-7",
    "claude-opus-4.7": "claude-opus-4-7",
    "claude-opus-4-7-20260416": "claude-opus-4-7",
    "opus-4.6": "claude-opus-4-6",
    "claude-opus-4.6": "claude-opus-4-6",
    "claude-opus-4-6-20251117": "claude-opus-4-6",
    "opus-4.5": "claude-opus-4-5",
    "claude-opus-4.5": "claude-opus-4-5",
    "claude-opus-4-5-20250120": "claude-opus-4-5",
    sonnet: "claude-sonnet-5",
    "sonnet-5": "claude-sonnet-5",
    "claude-sonnet-5": "claude-sonnet-5",
    "sonnet-4.6": "claude-sonnet-4-6",
    "claude-sonnet-4.6": "claude-sonnet-4-6",
    "claude-sonnet-4-6-20251117": "claude-sonnet-4-6",
    haiku: "claude-haiku-4-5",
    "haiku-4.5": "claude-haiku-4-5",
    "claude-haiku-4.5": "claude-haiku-4-5",
    "claude-haiku-4-5-20251001": "claude-haiku-4-5",
  },
  cursor: {
    auto: "auto",
    composer: "composer-2",
    "composer-2": "composer-2",
    "composer-1.5": "composer-1.5",
    "composer-1": "composer-1.5",
    "opus-4.6": "claude-opus-4-6",
    "opus-4.6-thinking": "claude-opus-4-6",
    "gpt-5.3": "gpt-5.3-codex",
    "codex-5.3": "gpt-5.3-codex",
    "gemini-3": "gemini-3-pro",
  },
  antigravity: {},
  droid: {
    droid: "claude-opus-4-8",
    factory: "claude-opus-4-8",
    opus: "claude-opus-4-8",
    "opus-4.8": "claude-opus-4-8",
    "opus-fast": "claude-opus-4-8-fast",
    "opus-4.8-fast": "claude-opus-4-8-fast",
    "opus-4.7": "claude-opus-4-7",
    "opus-4.7-fast": "claude-opus-4-7-fast",
    "opus-4.6": "claude-opus-4-6",
    sonnet: "claude-sonnet-5",
    "sonnet-5": "claude-sonnet-5",
    "sonnet-4.6": "claude-sonnet-4-6",
    "sonnet-4.5": "claude-sonnet-4-5-20250929",
    fable: "claude-fable-5",
    haiku: "claude-haiku-4-5-20251001",
    "5.5": "gpt-5.5",
    "5.5-fast": "gpt-5.5-fast",
    "5.5-pro": "gpt-5.5-pro",
    "5.4": "gpt-5.4",
    "5.4-fast": "gpt-5.4-fast",
    "5.4-mini": "gpt-5.4-mini",
    "5.3": "gpt-5.3-codex",
    "5.3-fast": "gpt-5.3-codex-fast",
    "gpt-5.3": "gpt-5.3-codex",
    "gemini-3-pro": "gemini-3.1-pro-preview",
    "gemini-3.1-pro": "gemini-3.1-pro-preview",
    "gemini-3.5-flash": "gemini-3.5-flash",
    "gemini-3-flash": "gemini-3-flash-preview",
    glm: "glm-5.2",
    "glm-5.2": "glm-5.2",
    "glm-5.1": "glm-5.1",
    nemotron: "nemotron-3-ultra",
    kimi: "kimi-k2.7-code",
    "kimi-code": "kimi-k2.7-code",
    deepseek: "deepseek-v4-pro",
    minimax: "minimax-m3",
  },
  grok: {
    grok: "grok-build-0.1",
    build: "grok-build-0.1",
    "grok-build-0.1": "grok-build-0.1",
    "grok-build": "grok-build",
    "4.3": "grok-build",
    "grok-4": "grok-build",
    "grok-4.3": "grok-build",
    "grok-latest": "grok-build",
    "grok-code-fast": "grok-build-0.1",
    "grok-code-fast-1": "grok-build-0.1",
    "grok-code-fast-1-0825": "grok-build-0.1",
    "code-fast": "grok-build-0.1",
  },
  kilo: {},
  opencode: {},
  pi: {},
};
